### ISSUE TITLE
mrustc requires extra nonessential qualification of a trait

### ISSUE THREAD

**Issue by danielrh** [thepowersgang/mrustc#104]
```rust
pub trait Allocator<T> {
    type AllocatedMemory : AllocatedSlice<T>;
}
pub trait AllocatedSlice<T>
    :  Default {
}
fn _simple_test<AllocU8:Allocator<u8>>(_a: AllocU8) {
  AllocU8::AllocatedMemory::default();
}
fn main(){}
```
The above fails with:
```Target Load: V V V
(0.00 s) Target Load: DONE
Parse: V V V
(0.00 s) Parse: DONE
LoadCrates: V V V
(0.22 s) LoadCrates: DONE
Expand: V V V
(0.00 s) Expand: DONE
- main: params.outfile = lib
Implicit Crates: V V V
(0.00 s) Implicit Crates: DONE
Resolve Use: V V V
(0.00 s) Resolve Use: DONE
Resolve Index: V V V
(0.00 s) Resolve Index: DONE
Resolve Absolute: V V V
(0.00 s) Resolve Absolute: DONE
HIR Lower: V V V
(0.00 s) HIR Lower: DONE
Resolve Type Aliases: V V V
(0.00 s) Resolve Type Aliases: DONE
Resolve Bind: V V V
(0.04 s) Resolve Bind: DONE
Resolve HIR Markings: V V V
(0.00 s) Resolve HIR Markings: DONE
Resolve UFCS paths: V V V
:0: error:0:Failed to find impl with 'default' for <AllocU8/*M:0*/ as ::Allocator<u8,>>::AllocatedMemory/*O*/ (in <<AllocU8/*M:0*/ as ::Allocator<u8,>>::AllocatedMemory/*O*/ as _>::default)
Aborted (core dumped)
```

but it can be repaired with some extra qualification:

```rust
pub trait Allocator<T> {
    type AllocatedMemory : AllocatedSlice<T>;
}
pub trait AllocatedSlice<T>
    :  Default {
}
fn _simple_test<AllocU8:Allocator<u8>>(_a: AllocU8) {
  <AllocU8::AllocatedMemory as Default>::default();
}
fn main(){}
```

**Comment by thepowersgang** [comment]
Can you try with the `nightly-1.29` branch? That has changes to how those paths are resolved that may fix this case.

**Comment by danielrh** [comment]
Yes nightly-1.29 branch works wonders

**Comment by elichai** [comment]
@thepowersgang I'm still getting similar things in current master.
```
> /home/elichai2/gits/mrustc/bin/mrustc testing/vendor/bitcoin_hashes/src/lib.rs -o output/libbitcoin_hashes-0_7_1.rlib --crate-name bitcoin_hashes --crate-type rlib -C emit-depfile=output/libbitcoin_hashes-0_7_1.rlib.d --crate-tag 0_7_1 -g --cfg debug_assertions -O -L output -L output --cfg feature=std --extern byteorder=output/libbyteorder-1_3_2.rlib
:0: error:0:Failed to find impl with 'default' for <Self/**/ as ::"bitcoin_hashes-0_7_1"::Hash>::Engine/*O*/ (in <<Self/**/ as ::"bitcoin_hashes-0_7_1"::Hash>::Engine/*O*/ as _>::default)

```
