### ISSUE TITLE
Incorrect codegen in librustc with GCC 5

### ISSUE THREAD

**Issue by thepowersgang** [thepowersgang/mrustc#63]
Seen both with GCC v5.5.0 and v5.4.0 (Linux Mint 18), x86-64

GCC's code generation for a particular function in librustc leads to uninitialised data being or-ed into the tag of an Option which is then matched upon and will abort due to the tag being neither 0 or 1.

_TODO: Obtain full details of which function causes the issue_

**Comment by thepowersgang** [comment]
Reproduced on Linux Mint 18.3 (`gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609`)

The abort is in `_ZRK$aL_ZN11collections3vec3Vec$aL_ZN5rustc3hir6ItemId$aR_as__ZN11collections3vec10SpecExtend$aL_ZN5rustc3hir6ItemId$C_ZN4core4iter3Map$aL_ZN4core4iter5Chain$aL_ZN4core4iter7sources4Once$aL_ZN6syntax3ast6NodeId$aR$C_ZN4core4iter3Map$aL_ZN4core5slice4Iter$aL_ZN6syntax7codemap7Spanned$aL_ZN6syntax3ast13PathListItem_$aR$aR$C_ZN5rustc12closure_I_82$aL_ZN5rustc3hir8lowering15LoweringContext$aR$aR$aR$C_ZN5rustc12closure_I_83$aL_ZN5rustc3hir8lowering15LoweringContext$aR$aR$aR$aRspec_extend`

**Comment by thepowersgang** [comment]
Offending codegen error function: `_ZRK$aL_ZN4core4iter3Map$aL_ZN4core4iter5Chain$aL_ZN4core4iter7sources4Once$aL_ZN6syntax3ast6NodeId$aR$C_ZN4core4iter3Map$aL_ZN4core5slice4Iter$aL_ZN6syntax7codemap7Spanned$aL_ZN6syntax3ast13PathListItem_$aR$aR$C_ZN5rustc12closure_I_82$aL_ZN5rustc3hir8lowering15LoweringContext$aR$aR$aR$C_ZN5rustc12closure_I_83$aL_ZN5rustc3hir8lowering15LoweringContext$aR$aR_as__ZN4core4iter8iterator8Iterator$aRnext`

In this function, there is a path through the function where the `%rbx` register is never assigned, and is or-ed into the return value (`%rax`). This path is hit if the state of Chain is `ChainState::Back` (i.e. the Once is complete, and we're on to running `map` on the `slice::Iter`

**Comment by thepowersgang** [comment]
Known good/bad compilers:
Good:
* gcc 6.2.0
* gcc 6.3.0 (travis)
* gcc 7.2.0 (ubuntu latest)

Bad
* gcc 5.4.0 (Ubuntu 16.04 / Mint 18)

**Comment by thepowersgang** [comment]
Diff between failing and passing C code
```
255c255,258
<       struct s__ZN4core6option12Option$HSome$aL$Rs_u32$aR var_1;
---
>       union {
>               tUNIT var_0;
>               struct s__ZN4core6option12Option$HSome$aL$Rs_u32$aR var_1;
>       } DATA;
258,259c261,262
<       if( (*rv).var_1._0 != 0 ) {
<               _ZRI$aL_ZN4core6option12Option$HSome$aL$Rs_u32$aR$aR11$Hdrop_glue(&(*rv).var_1);
---
>       if( (*rv).DATA.var_1._0 != 0 ) {
>               _ZRI$aL_ZN4core6option12Option$HSome$aL$Rs_u32$aR$aR11$Hdrop_glue(&(*rv).DATA.var_1);
652c655
<       if( arg0.var_1._0 != 0 )
---
>       if( arg0.DATA.var_1._0 != 0 )
666c669
<       var1._0 = (*arg0.var_1._0);     // Local(1) = Struct(::"core"::option::Option#Some<u32,>, {Deref(Field(0, Downcast(1, Argument(0))))})
---
>       var1._0 = (*arg0.DATA.var_1._0);        // Local(1) = Struct(::"core"::option::Option#Some<u32,>, {Deref(Field(0, Downcast(1, Argument(0))))})
931c934
<       var3.var_1 = var7;      // Local(3) = Variant(::"core"::option::Option<&u32,> #1, Local(7))
---
>       var3.DATA.var_1 = var7; // Local(3) = Variant(::"core"::option::Option<&u32,> #1, Local(7))
```

It appears that just having the union in this case causes the incorrect codegen.

**Comment by thepowersgang** [comment]
Fixed in 363e6fa (tested on Mint 18)

**Comment by aclemons** [comment]
I've just retested on GCC 5.5.0 on Slackware 14.2. It still fails here building 8a64df3.

```
[RUSTC] -o prefix/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore.rlib
Command terminated by signal 6
```

What extra information can I give you to help diagnose?

**Comment by aclemons** [comment]
Tests are passing:
```
$ make local_tests
make[1]: Entering directory '/tmp/aclemons/mrustc-8a64df35a605394fdc969b7abb2702a810d740e5/tools/testrunner'
[CXX] main.cpp
[CXX] ../minicargo/path.cpp
[CXX] -o ../bin/testrunner
make[1]: Leaving directory '/tmp/aclemons/mrustc-8a64df35a605394fdc969b7abb2702a810d740e5/tools/testrunner'
./tools/bin/testrunner -o output/local_tests samples/test
Calling mrustc -L output -L output/local_tests/deps-for_underscore_drop -o output/local_tests/for_underscore_drop.exe samples/test/for_underscore_drop.rs --test
Calling output/local_tests/for_underscore_drop.exe
Calling mrustc -L output -L output/local_tests/deps-gcc5_codegen_bug -o output/local_tests/gcc5_codegen_bug.exe samples/test/gcc5_codegen_bug.rs -O
Calling output/local_tests/gcc5_codegen_bug.exe
Calling mrustc -L output -L output/local_tests/deps-inline_copy_values -o output/local_tests/inline_copy_values.exe samples/test/inline_copy_values.rs --test
Calling output/local_tests/inline_copy_values.exe
Calling mrustc -L output -L output/local_tests/deps-issue-mrustc-62 -o output/local_tests/issue-mrustc-62.exe samples/test/issue-mrustc-62.rs
Calling output/local_tests/issue-mrustc-62.exe
Calling mrustc -L output -L output/local_tests/deps-misc_macro_issues -o output/local_tests/misc_macro_issues.exe samples/test/misc_macro_issues.rs --test
Calling output/local_tests/misc_macro_issues.exe
Calling mrustc -L output -L output/local_tests/deps-scoping_rules -o output/local_tests/scoping_rules.exe samples/test/scoping_rules.rs --test
Calling output/local_tests/scoping_rules.exe
TESTS COMPLETED
6 passed, 0 failed, 0 errored, 0 skipped
```

These are the first few lines (there are many more):
```
#0  0x00007ffff6b923f8 in raise () from /lib64/libc.so.6
#1  0x00007ffff6b93ffa in abort () from /lib64/libc.so.6
#2  0x00000000006ff569 in _ZN11panic_abort3$H05abort () at output/libpanic_abort.hir.o.c:91
#3  0x00000000006ff599 in __rust_start_panic (arg0=<optimized out>, arg1=<optimized out>) at output/libpanic_abort.hir.o.c:120
#4  0x0000000000582b59 in rust_panic (arg0=...) at output/libstd.hir.o.c:63518
#5  0x0000000000583a75 in _ZN3std9panicking20rust_panic_with_hook (arg0=..., arg1=arg1@entry=0x7ffff692ed80) at output/libstd.hir.o.c:63707
#6  0x0000000000583acb in _ZN3std9panicking11begin_panic$aL_ZN11collections6string6String$aR (arg0=..., arg1=arg1@entry=0x7ffff692ed80) at output/libstd.hir.o.c:63189
#7  0x0000000000583b45 in _ZN3std9panicking15begin_panic_fmt (arg0=arg0@entry=0x7ffff692edb0, arg1=arg1@entry=0x7ffff692ed80) at output/libstd.hir.o.c:63246
#8  0x0000000000583d2e in rust_begin_unwind (arg0=..., arg1=..., arg2=<optimized out>) at output/libstd.hir.o.c:63489
#9  0x0000000000bcbc9e in _ZN4core9panicking9panic_fmt (arg0=..., arg1=<optimized out>) at output/rustc-build/librustc.hir.o.c:459090
#10 0x0000000000c032d5 in _ZN4core6result13unwrap_failed$aL_ZN11collections6string6String$aR (arg1=..., arg0=...) at output/rustc-build/librustc.hir.o.c:467165
#11 _ZRI$aL_ZN4core6result6Result$aL_ZN5rustc2ty6layout5Align$C_ZN11collections6string6String$aR$aR6unwrap (arg0=...) at output/rustc-build/librustc.hir.o.c:16244
#12 0x0000000000d7f35a in _ZRI$aL_ZN5rustc2ty6layout6Struct$aR3new (arg0=0x7ffff69362a0, arg1=arg1@entry=0x7ffff692f5c0, arg2=<optimized out>, arg3=..., arg4=0x7fffde89bee0)
    at output/rustc-build/librustc.hir.o.c:1262919
#13 0x0000000000f28034 in _ZRI$aL_ZN5rustc2ty6layout6Layout$aR16compute_uncached (arg0=..., arg1=..., arg2=arg2@entry=0x7fffde89bee0) at output/rustc-build/librustc.hir.o.c:1257924
#14 0x0000000000f29b74 in _ZN5rustc2ty4util10layout_raw (arg0=..., arg1=...) at output/rustc-build/librustc.hir.o.c:654812
#15 0x0000000000cb5477 in _ZRK$aL_ZN5rustc13closure_I_703$aL_ZN5rustc2ty4maps7queries10layout_raw$Cfn_1_$Rs__ZN4core6result6Result$aL$Rs__ZN5rustc2ty6layout6Layout$C_ZN5rustc2ty6layout11LayoutError$aR__ZN4core6result6Result$aL$Rs__ZN5rustc2ty6layout6Layout$C_ZN5rustc2ty6layout11LayoutError$aR$C_ZN4core6result6Result$aL$Rs__ZN5rustc2ty6layout6Layout$C_ZN5rustc2ty6layout11LayoutError$aR$aR_as__ZN4core3ops2Fn$aL$T0$aR$aR4call (arg0=arg0@entry=0x7ffff692fda0, arg1=...) at output/rustc-build/librustc.hir.o.c:1917371
#16 0x0000000000d8cc51 in _ZRI$aL_ZN5rustc2ty7context6TyCtxt$aR11cycle_check$aL_ZN5rustc13closure_I_703$aL_ZN5rustc2ty4maps7queries10layout_raw$Cfn_1_$Rs__ZN4core6result6Result$aL$Rs__ZN5rustc2ty6layout6Layout$C_ZN5rustc2ty6layout11LayoutError$aR__ZN4core6result6Result$aL$Rs__ZN5rustc2ty6layout6Layout$C_ZN5rustc2ty6layout11LayoutError$aR$C_ZN4core6result6Result$aL$Rs__ZN5rustc2ty6layout6Layout$C_ZN5rustc2ty6layout11LayoutError$aR$aR$C_ZN4core6result6Result$aL$Rs__ZN5rustc2ty6layout6Layout$C_ZN5rustc2ty6layout11LayoutError$aR$aR (arg0=...,
    arg1=..., arg2=..., arg3=...) at output/rustc-build/librustc.hir.o.c:1236010
#17 0x0000000000d8d17b in _ZRI$aL_ZN5rustc2ty4maps7queries10layout_raw$aR12try_get_with$aLfn_1_$Rs__ZN4core6result6Result$aL$Rs__ZN5rustc2ty6layout6Layout$C_ZN5rustc2ty6layout11LayoutError$aR__ZN4core6result6Result$aL$Rs__ZN5rustc2ty6layout6Layout$C_ZN5rustc2ty6layout11LayoutError$aR$C_ZN4core6result6Result$aL$Rs__ZN5rustc2ty6layout6Layout$C_ZN5rustc2ty6layout11LayoutError$aR$aR (arg0=..., arg1=..., arg2=...,
    arg3=arg3@entry=0xd7cb30 <_ZRK$aL_ZN4core6result6Result$aL$Rs__ZN5rustc2ty6layout6Layout$C_ZN5rustc2ty6layout11LayoutError$aR_as__ZN4core5clone5Clone$aR5clone>)
    at output/rustc-build/librustc.hir.o.c:1291556
#18 0x0000000000d8d465 in _ZRI$aL_ZN5rustc2ty4maps7queries10layout_raw$aR7try_get (arg0=..., arg1=..., arg2=...) at output/rustc-build/librustc.hir.o.c:1291119
#19 0x0000000000e2d974 in _ZRI$aL_ZN5rustc2ty4maps8TyCtxtAt$aR10layout_raw (arg0=..., arg1=...) at output/rustc-build/librustc.hir.o.c:1268754
#20 0x0000000000ecb70d in _ZRI$aL_ZN5rustc2ty3TyS$aR6layout (arg0=0x7fffde89bee0, arg1=..., arg2=...) at output/rustc-build/librustc.hir.o.c:1211437
#21 0x0000000000f1f161 in _ZRI$aL_ZN5rustc2ty6layout12SizeSkeleton$aR7compute (arg0=0x7fffde89bee0, arg1=..., arg2=...) at output/rustc-build/librustc.hir.o.c:1261543
#22 0x0000000000f1f833 in _ZRI$aL_ZN5rustc6middle11intrinsicck11ExprVisitor$aR15check_transmute (arg0=arg0@entry=0x7ffff6930e40, arg1=..., arg2=0x7fffde89bee0, arg3=0x7ffff2f97c30)
    at output/rustc-build/librustc.hir.o.c:1134876
#23 0x0000000000f20177 in _ZRK$aL_ZN5rustc6middle11intrinsicck11ExprVisitor_as__ZN5rustc3hir10intravisit7Visitor$aR10visit_expr (arg0=arg0@entry=0x7ffff6930e40, arg1=0x7fffd8dd5900)
    at output/rustc-build/librustc.hir.o.c:2054551
#24 0x0000000000f23f4c in _ZN5rustc3hir10intravisit9walk_expr$aL_ZN5rustc6middle11intrinsicck11ExprVisitor$aR (arg0=arg0@entry=0x7ffff6930e40, arg1=arg1@entry=0x7fffd8dd5d00)
    at output/rustc-build/librustc.hir.o.c:494202
#25 0x0000000000f20182 in _ZRK$aL_ZN5rustc6middle11intrinsicck11ExprVisitor_as__ZN5rustc3hir10intravisit7Visitor$aR10visit_expr (arg0=arg0@entry=0x7ffff6930e40, arg1=0x7fffd8dd5d00)
    at output/rustc-build/librustc.hir.o.c:2054452
#26 0x0000000000f23871 in _ZN5rustc3hir10intravisit10walk_block$aL_ZN5rustc6middle11intrinsicck11ExprVisitor$aR (arg0=0x7ffff6930e40, arg1=0x7fffd8dd5d70)
    at output/rustc-build/librustc.hir.o.c:482718
#27 0x0000000000f23c78 in _ZN5rustc3hir10intravisit9walk_expr$aL_ZN5rustc6middle11intrinsicck11ExprVisitor$aR (arg0=arg0@entry=0x7ffff6930e40, arg1=arg1@entry=0x7fffd8e220e0)
    at output/rustc-build/librustc.hir.o.c:493849
#28 0x0000000000f20182 in _ZRK$aL_ZN5rustc6middle11intrinsicck11ExprVisitor_as__ZN5rustc3hir10intravisit7Visitor$aR10visit_expr (arg0=arg0@entry=0x7ffff6930e40,
    arg1=arg1@entry=0x7fffd8e220e0) at output/rustc-build/librustc.hir.o.c:2054452
#29 0x0000000000f2026c in _ZN5rustc3hir10intravisit9walk_body$aL_ZN5rustc6middle11intrinsicck11ExprVisitor$aR (arg0=arg0@entry=0x7ffff6930e40, arg1=arg1@entry=0x7fffd8e220d0)
    at output/rustc-build/librustc.hir.o.c:484363
```

I'll send you links to the generated c files.

**Comment by thepowersgang** [comment]
That's a clean panic (from an unwrap on None)... but with no message printed. Can you open a new ticket about that?

**Comment by aclemons** [comment]
Done (#66), thanks.
